### ISSUE TITLE
undefined local variable or method `relation_metadata'

### ISSUE THREAD

**Issue by tirdadc** [aq1018/mongoid-history#135]
```ruby
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include Mongoid::History::Trackable
  belongs_to :user
  embeds_one :transaction
  
  # some regular fields, some attr_accessors, and also some accepts_nested_attributes_for
  ...
  track_history on: :all
end
```

I have the rest set up normally (ie app/models/history_tracker.rb and config/initializers/mongoid-history.rb) but I get this error when I attempt to update an existing item. I'm using 0.4.7 and mongoid 4.0.0.

```
NameError - undefined local variable or method `relation_metadata' for #<Item:0x007f94b43c56e0>:
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/attributes/dynamic.rb:136:in `method_missing'
  mongoid-history (0.4.7) lib/mongoid/history/trackable.rb:158:in `related_scope'
  mongoid-history (0.4.7) lib/mongoid/history/trackable.rb:230:in `history_tracker_attributes'
  mongoid-history (0.4.7) lib/mongoid/history/trackable.rb:282:in `track_history_for_action'
  mongoid-history (0.4.7) lib/mongoid/history/trackable.rb:246:in `track_update'
  activesupport (4.0.11) lib/active_support/callbacks.rb:387:in `_run__3665827704520130637__update__callbacks'
  activesupport (4.0.11) lib/active_support/callbacks.rb:80:in `run_callbacks'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/interceptable.rb:132:in `run_callbacks'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:142:in `block in prepare_update'
  activesupport (4.0.11) lib/active_support/callbacks.rb:383:in `_run__3665827704520130637__save__callbacks'
  activesupport (4.0.11) lib/active_support/callbacks.rb:80:in `run_callbacks'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/interceptable.rb:132:in `run_callbacks'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:141:in `prepare_update'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:24:in `update_document'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/savable.rb:25:in `save'
   () Users/tirdad/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mongoid-88599cf64c3d/lib/mongoid/persistable/updatable.rb:78:in `update'
  app/models/item.rb:343:in `update_attributes'
```

I assumed this was because of the dynamic attributes, so I changed the tracking to only happen on 2 fields. It still didn't work.

**Comment by dblock** [comment]
Try this with HEAD, dynamic attributes are now fully supported.

**Comment by tirdadc** [comment]
Did you mean master? I tried with 

`gem 'mongoid-history', git: 'https://github.com/aq1018/mongoid-history.git', branch: 'master'`

in my Gemfile, but it's no different, seems like it's not done yet?

https://github.com/aq1018/mongoid-history/compare/master...0.4.7-cut

**Comment by dblock** [comment]
Yes, master. If you put together a repro that I can play with I can try to help.

**Comment by tirdadc** [comment]
Tried on a different model that doesn't have dynamic attributes, got the same error. I'll post a gist of that model and the controller code.

**Comment by dblock** [comment]
There's nothing wrong in your model. Can you put a tiny project up that reproduces this?

**Comment by tirdadc** [comment]
I will try to post this tomorrow on Github.

**Comment by sivagollapalli** [comment]
@dblock I think it works fine dynamic attributes. Also, we already included spec https://github.com/aq1018/mongoid-history/blob/master/spec/unit/trackable_spec.rb#L109 . Perhaps, we can close this issue.

**Comment by dblock** [comment]
That looks reasonable @sivagollapalli, closing.
