### ISSUE TITLE
NameError: wrong constant name 

### ISSUE THREAD

**Issue by sahilchopra** [aq1018/mongoid-history#146]
Person Model

```
class Person
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::History::Trackable

  field :first_name,              type: String
  field :last_name,               type: String
  track_history   :on => [:first_name, :aliases]     # track document destruction, default is false


end
```

```
Person.last.update_attributes(:first_name => "test2")
```

Logs

```
NameError: uninitialized constant HistoryTracker
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/mongoid-history-0.4.1/lib/mongoid/history.rb:11:in `tracker_class'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/mongoid-history-0.4.1/lib/mongoid/history/trackable.rb:242:in `track_history_for_action'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/mongoid-history-0.4.1/lib/mongoid/history/trackable.rb:206:in `track_update'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:164:in `block in halting'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `block in call'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `each'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/sahil/.rvm/gems/ruby-2.3.0@latest/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_update_callbacks''
```

**Comment by dblock** [comment]
You are required to create a `HistoryTracker` class, see https://github.com/aq1018/mongoid-history/blob/6948018dd3cb8f47be6638510244349cf959a4c4/README.md#usage. I am not against providing a default, but I think this was introduced to make sure people are aware they are storing data in some other collection.
